apiVersion: v1
kind: Service
metadata:
  name: webapp2
  labels:
    app: webapp2
spec:
  selector:
    app: webapp2
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080   # open this in your EC2 security group
